
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: treasury_app
    expose:
      - "9000"
    networks:
    - treasury        # ← ADD THIS

  redis:
    image: redis:latest
    container_name: treasury_redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - treasury
    restart: unless-stopped

  pgsql:
    image: postgres:16.3
    container_name: treasury_pgsql
    environment:
      POSTGRES_DB: treasury_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leonio
    # Named volume ensures DB persists after container is removed
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - treasury
    restart: unless-stopped

networks:
  treasury:
    driver: bridge

volumes:
  pgdata: